### ISSUE TITLE
Cannot play youtube video on mobile safari

### ISSUE THREAD

**Issue by PriaBrock** [pupunzi/jquery.mb.YTPlayer#100]
Hi,

I have problem with play the youtube video on safari browser on mobile devices. It seems that the player doesn't start to playing the video. Only black screen appears with youtube credentials about the video, but nothing happen. On desktop it works, so I guess there are some limitations in the mobile version of Safari, which I'm not aware of. Do you know anything that can cause such a problem? I have a custom overlay over the video which is showing and hiding depending the state of video. But I dont think that this should by a problem, because it calls native player API.

**Comment by bhamodi** [comment]
Hi there,

I believe that videos are disabled for mobile devices simply due to the amount of network speeds required to display a YouTube video without lag.

In fact, in the code - there is a check if the browser is a mobile browser and if so, the video player gets destroyed and an overlay image is displayed instead. Take a look here:
https://github.com/pupunzi/jquery.mb.YTPlayer/blob/master/inc/jquery.mb.YTPlayer.js#L218

If you really want to give your users a YouTube video on mobile, you could just eliminate the code that checks for mobile devices and disables the video player.

**Comment by pupunzi** [comment]
Hi,
The YTPlayer would not work on mobile devices due to vendors policy on javascript media controls; you should provide a background image as fall back for mobiles
