### ISSUE TITLE
Broken with bootstrap?

### ISSUE THREAD

**Issue by dwendt** [pupunzi/jquery.mb.YTPlayer#106]
Is there some documentation missing on what specific CSS a container needs to have for this to work? I can't seem to get it right. It won't work applied to any element here...

http://jsfiddle.net/wzqk7c7o/1/

**Comment by pupunzi** [comment]
Hi,
I just make a jsfiddle (http://jsfiddle.net/pupunzi/30az41ok/) using your code but pointing to the github files for the plug-in and to the same Bootstrap link as in your example and it's working fine; in your example you are getting an error that prevents the script to work. There are no conflicts with Bootstrap (I used it hundreds of time together with Bootstrap).

Anyway it would be better for you to create a real test page on a web-server pointing to local js, css, and font files instead of using jsfiddle.

You can download the latest release (https://github.com/pupunzi/jquery.mb.YTPlayer/archive/master.zip not yet in production) and you can consult the documentation here: https://github.com/pupunzi/jquery.mb.YTPlayer/wiki

Bye,
Matteo


––––––––––––––––––––––––––––––––––––––––––––––––––
If you like this plugin and you are satisfied by the support, please consider a donation. It's always appreciated and can guaranty the development.
