### ISSUE TITLE
video in mobile

### ISSUE THREAD

**Issue by benklinger** [pupunzi/jquery.mb.YTPlayer#124]
I can see the video from youtube and the controllers. when I press play, the player changes but the video doesn't play. Is there a way to workaround this? I want it to be just a regular video on mobile and not background.

**Comment by burnsyboo** [comment]
It says on the wiki the background will not work on mobile only Desktop

http://prntscr.com/7u8di0

This is not an issue Mobile Devices unfortunately do not allow background videos etc.

i think this is due to the way the browsers is built 

I hope this helps 

Kind Regards
Hayden

**Comment by ukdna** [comment]
I had to comment on this issue because Hayden did not firstly read correctly the subject matter and give an appropriate answer to the specific question!

We also are looking for this same solution to our web application. We realise that the back ground video architecture is not currently available on mobile; however, we too would like to offer a 'fall back' option which (on mobile & tablet only) will playing the video which works in the background on PC & Desktop. 

Please visit: http://tiny.cc/whatsOn

From a desktop or pc you will be able to use all the normal functions.

How can we 'on mobile' default to a 'YouTube playlist' we know it can be done because your able to view youtube playlist on mobile but we don't currently posses the scripting knowledge.

Please email ukdna@ymail.com if you can guide us in the right direction or post your answer here. We will also credit you on the website if yours is the solution we choose:)

**Comment by burnsyboo** [comment]
@ukdna that was my fault for not correctly responding to the issue i read over the issue to fast and i am sorry for this
