### ISSUE TITLE
Video not looping fully

### ISSUE THREAD

**Issue by live-mesh** [pupunzi/jquery.mb.YTPlayer#150]
One of our customers reports that, when looping, some parts specially towards the end of the video gets skipped. I noticed that the latest version of the player too has the skipping problem and does it consistently unlike the previous versions where it is random. 

Here is a test page created to check the video background - 

http://portfoliotheme.org/wired/page-section/video-test/

**Comment by pupunzi** [comment]
Hi,
The problem is that the video you are pointing to is too short (4:00 sec); you should consider that the component cut the first and the last second to prevent the black screen at the beginning and the end of the stream at the end; so you have 2 seconds for your loop; the component check for the video state every 100 milliseconds if the control bar is visible or every 500 milliseconds if the control bar is hidden that influence the real stop and start time. It is not a client application for video editing and the video is streamed on the web where connection time, bandwidth and several other issue can cause unwanted behavior. I'll publish an update with some optimization but you'll never have the precision you are asking for.

Bye,
Matteo
