### ISSUE TITLE
Fullscreen video "losing edges"

### ISSUE THREAD

**Issue by Anderuimm** [pupunzi/jquery.mb.YTPlayer#191]
Using this:

data-property="{ videoURL : 'https://www.youtube.com/watch?v=JHdxEqp1xdw' , containment : '#home-background-video' ,ratio: '4/3', realfullscreen : false, mute : 0, startAt : 0.1, stopAt : 0, opacity : 1, optimizeDisplay: true,addRaster: false, autoPlay : true, vol: 100, showControls: false, loop: 1}"

The background video appears to be zoomed in on it.

Original video image:
![image](https://cloud.githubusercontent.com/assets/3143872/16341584/484fd472-3a04-11e6-8cd8-0f61c87c97de.png)

On the page appears like:
![image](https://cloud.githubusercontent.com/assets/3143872/16341596/5b17b02a-3a04-11e6-8e7e-d45ccb394518.png)

I've double checked my CSS and there isn't any fixed width, and when I try to "responsive" the page the problem still happens.

**Comment by pupunzi** [comment]
Hi,
Using this component as background by default the video size is managed to let it cover all the screen surface cropping the differences between the screen (or the container) and the video aspect ratio. If you don't want that behavior and you need to see all the video whatever is the size of the screen you can **turn off the "optimizeDisplay" option**. That way instead of cropping the video you'll see black bars on left/right or top/bottom depending on the screen size.
