### ISSUE TITLE
Uncaught TypeError: jQuery(...).YTPlayer is not a function

### ISSUE THREAD

**Issue by iamjohnshaw** [pupunzi/jquery.mb.YTPlayer#212]
Hi there,

Pupunzi - trying to implement your script with no joy, getting an YTPlayer is not a function error.
I realise it's something to do with the loading order, but as far as I can see it's copied exactly from your code (apart from the YouTube URL).

The code itself is set up on the Master template of an Umbraco CMS site.

You can see the dev-site implementation here: 
http://gp-dev.clientdevweb.co.uk/

The video panel is just above the footer -
Your help is appreciated

Thanks
John

**Comment by pupunzi** [comment]
Hi,
I notice that you have several elements on your page with the same "**customElement**" ID where you want to initialize the player. They should have different IDs (the ID must be unique inside a page).

I'm getting another error on your page:
**Uncaught TypeError: a.indexOf is not a function**
And it doesn't seam caused by the YTPlayer script... Probably also that is blocking the correct YTPlayer script behaviour...

Bye,
Matteo

**Comment by iamjohnshaw** [comment]
Sorry - you must have looked as I was testing something. I've put it back as per your instructions and still got the issue. Must be a conflict on our site somewhere - will comment out some of our functions and retest - 

Thanks
John
