### ISSUE TITLE
Javascript error ytcfg is not defined(…)

### ISSUE THREAD

**Issue by msimone79** [pupunzi/jquery.mb.YTPlayer#217]
while loading a youtube video I get this error:

`Uncaught ReferenceError: ytcfg is not defined`

this is the code I use to embed the video as backgroung in html page:

`<div id="bgndVideo" class="player" data-poster="img/img.jpg" data-property="{videoURL:'--------------',containment:'body', autoPlay:true, showControls:false, mute:true, startAt:0, opacity:1}"></div> `

How can I fix this problem?
Thanks in advance 

Matteo

**Comment by beany-vu** [comment]
It seems to be the error from "Youtube API" rather than "YTPlayer". I also got this issue some days ago and didn't get it before. 
I try to access this URL and I can see this error:  https://www.youtube.com/embed/lcHs77TM2ygmodestbranding=1&autoplay=0&controls=0&showinfo=0&rel=0&enablejsapi=1&version=3&playerapiid=mbYTP_herovideo&origin=http%3A%2F%2Fsportroops.local&allowfullscreen=true&wmode=transparent&iv_load_policy=3&html5=1&widgetid=1

**Comment by pupunzi** [comment]
Yes, it's a bug on the Youtube API; hope they'll fix it soon.
Fortunately it is not blocking :-)
