### ISSUE TITLE
Not working on mobile when set as div background

### ISSUE THREAD

**Issue by arkid** [pupunzi/jquery.mb.YTPlayer#224]
I have a video loading contained within the background of a div on my page.   This works great on all desktop browsers but the div doesn't appear at all when viewed on mobiles.

I saw another issue where it appeared to be the flash youtube player being the cause.  I can confirm that this isn't the issue here as it's definitely the html5 player that is loading.

My code is...

`<div id="homepage100_1" class="h100video" data-property="{videoURL:'aUfegKk09RM',containment:'#homepage100_1',autoPlay:true, mute:false, startAt:0, opacity:1, stopMovieOnBlur:false, showYTLogo:false, showControls:false}"></div>`

`<script src="jquery.mb.YTPlayer.min.js"></script><script>
jQuery(function(){
	  jQuery("#homepage100_1").YTPlayer();
	});
</script>`

**Comment by pupunzi** [comment]
The YTPlayer plug-in doesn't work on mobile devices. It falls back to the default YT player only if the  YTPlayer method is invoked with the containment set as "self" otherwise it should use the "mobileFallbackImage" as fallback.

All the best,
Matteo

**Comment by arkid** [comment]
Hi Matteo  
Just for the record, what is the reason for the player not working on mobile ?     

Also just to clarify, when you talk about the "deafult yt player" do you mean the flash one ?

**Comment by pupunzi** [comment]
Hi,
This plug-in can't work on mobile because of their restrictions on the use of API to control the video via javascript. Audio and Video media are managed by the main device player and can't be controlled using javascript to prevent the unwanted use of bandwidth. Therefore the video can't be played as background.

By default player I mean the default Youtube player used by the mobile devices (with the main control bar and without the javascript integration).

All the best,
Matteo
