### ISSUE TITLE
Issue with YTPChangeMovie [Object doesn't support property or method 'toFixed']

### ISSUE THREAD

**Issue by rtarson** [pupunzi/jquery.mb.YTPlayer#240]
The code worked before and haven't did any changes to the thing, but now I keep getting error below when putting in a successful YT URL. If I apply the changed youtube url a few more times it eventually works but is glitchy. I Cannot figure out why this is? Any help would be appreciated.
The Error(base.js is coming from YouTube Script) : 
```
SCRIPT438: Object doesn't support property or method 'toFixed'
base.js (1303,459)
``````
The part that changes the video:
```
$('#yt-player').YTPChangeMovie({
         videoURL: ytURL,
         ratio: rat,
         startAt: sTime
      });

```

**Comment by rtarson** [comment]
I think I solved

**Comment by pupunzi** [comment]
Do you have a public URL where the issue is happening?

**Comment by rtarson** [comment]
Yeah it's on codepen. I'm making a advanced filter so people know more about API. It worked before but I'm wondering if it's because iframe causing it. I recently updated jQuery and MB.YTPlayer to see if that was the issue. I used your API for about a year 1st time experiencing this issue.

Check it out here: http://codepen.io/RTarson/pen/rLapGL

**Comment by pupunzi** [comment]
Hi,
Thank you :-)

The method **.toFixed()** is used by the jquery.mb.simpleSlider.js implemented to manage the volume control in the player. It's used also on the filters slider in my demo page.
I think the issue is due to a non numeric value set by one of the slider you are using too and not from the base.js... 

Anyway on your CodePen demo I'm not able to reproduce the issue...

I would check the values of the sliders first to see if one of them has something wrongly set.

Let me know.
M

**Comment by rtarson** [comment]
@pupunzi Thank You so much for the tip. Yeah I was wondering why the volume was so touchy. I will look into it and see whats going on? But you were able to apply a different movie?

**Comment by pupunzi** [comment]
Oh.. yes, I tried now and changing the movie I get the error...
It doesn't happens on my demo... so it should be something related to the way you are implementing it... I'll take a deeper look.

**Comment by rtarson** [comment]
Thank You, so much! I been trying to figure it out for the longest time.

**Comment by pupunzi** [comment]
Here is the fix:
the startAt as the stopAt value must be a number and this is what the Youtube API expect.  
few lines above the YTPChangeMovie call you are checking if the value of the startAt is set otherwise you set the default:

```
   if ($('#startTime').val() !== '') {
      sTime = $('#startTime').val();
   } else {
      sTime = '0';
   }
```
But you are setting it as a string.

So the best is to force the value to a number:

```
     $('#yt-player').YTPChangeMovie({
         videoURL: ytURL,
         ratio: rat,
         startAt: parseFloat(sTime)
      });
```

But you should set the default to a number and not to a string:

```
   if ($('#startTime').val() !== '') {
      sTime = $('#startTime').val();
   } else {
      sTime = 0;
   }
```

All the best,
M

**Comment by rtarson** [comment]
@pupunzi Thank You so much. Not sure why I set that to string anyways. Thank you so much for doing that!
