### ISSUE TITLE
OnYouTubeIframeAPIReady Not Calling In Webpack environments

### ISSUE THREAD

**Issue by centrual** [pupunzi/jquery.mb.YTPlayer#246]
Hello,

`onYouTubeIframeAPIReady` function not available in window if you building with webpack. Here is a solution:

``` javascript
function onYouTubeIframeAPIReady() { /* ... */ }
// to
window.onYouTubeIframeAPIReady = function onYouTubeIframeAPIReady() { /* ... */ }
```

**Comment by pupunzi** [comment]
Hi,
Thanks for this solution and to make it available for anyone that is using Webpack.
Instead of changing the jquery.mb.YTPlayer.js you could have on your script loaded after the YTPlayer one something like:

`window.onYouTubeIframeAPIReady = onYouTubeIframeAPIReady;`

That should work the same as you are redefining the function on the window element.
