### ISSUE TITLE
Poor quality video

### ISSUE THREAD

**Issue by vladvi** [pupunzi/jquery.mb.YTPlayer#252]
At the first entrance to the site http://alekseiptitsa.com/ the video is displayed in poor quality, although the settings are quality: 'hd1080'. Version of plugin 3.0.16. What could be the reason?

**Comment by pupunzi** [comment]
The video quality you set is not mandatory for Youtube. If you have enough bandwidth the quality you set will be respected, otherwise Youtube set the correct quality for your connection speed.
The video in your page for me is high quality since the first second; probably you have a slow connection and that's why the video starts with a poor quality.
