### ISSUE TITLE
div instead iframe

### ISSUE THREAD

**Issue by VadLogan** [pupunzi/jquery.mb.YTPlayer#283]
Hi there, why i have a div tag instead iframe

**Comment by pupunzi** [comment]
Hi,
the DIV element is used to store the background video properties; the Youtube background video is then create via javascript using that properties .

**Comment by tleifj** [comment]
Hello,

I know this is closed, but I think I may be having the same problem as the OP. For some reason, sometimes the element that is created via JS will be a div element instead of the iframe with the video. 

For example, I initiate the video player using the div with properties like: 

`<div id="bgndVideo" class="player" data-property="{videoURL:''video_url ',containment:'#masthead',autoPlay:true, mute:true, stopMovieOnBlur: false, showYTLogo: false, showControls: false, abundance: 0.3}"></div>`

and the output is:
`<div id="iframe_bgndVideo" class="playerBox" style="position: absolute; z-index: 0; width: 100%; height: 100%; top: 0px; left: 0px; overflow: hidden; opacity: 1;"></div>`

This should be an iframe element with the src attribute, but it's simply a div.

Any idea why that would happen?

**Comment by pupunzi** [comment]
If that happens, for some reason the YT API do not inject the iframe on your page. Check if you have errors in console.

**Comment by tleifj** [comment]
Thanks for the reply. Unfortunately there are no console errors :/. I've also implemented a background video on another page on the same site with the same YT video and it works there. 

Do you know if there is any YT API debugging I can do within your library or in general to see where the error is? Thank you!

**Comment by pupunzi** [comment]
I should see the page to have a chance to understand what could be the problem

**Comment by tleifj** [comment]
Hello,

It looks like a WordPress carousel plugin (Soliloquy) was preventing the iframe from being injected for some reason. I removed it and it works now.
