### ISSUE TITLE
Problem with loop

### ISSUE THREAD

**Issue by dbagnai** [pupunzi/jquery.mb.YTPlayer#297]
I've the demo project on my server,
i modified only to start video near end,
but although loop:false in data-property
the video continue to start and often i hear only the music not seeing
video.
http://testsite30.weapps.eu/examples/demo_multiple_videos.html

This on chrome
Versione 61.0.3163.100 (Build ufficiale) (a 64 bit)

**Comment by pupunzi** [comment]
I just made a test using exactly your code but with the latest mb.YTPlayer Master release and I can't reproduce the issue...
Can you try using the Master copy of the script (build: 6427) instead of the latest public release (build: 6408) ?
You can download it from here: 
https://github.com/pupunzi/jquery.mb.YTPlayer/archive/master.zip

Thank you,
M

**Comment by dbagnai** [comment]
Ok with the Master version the loop is correctly stopping after end of video,
you can see here:
http://testsite29.weapps.eu/examples/demo_multiple_videos.html

while in this with the public release loop don't work in chrome:
http://testsite30.weapps.eu/examples/demo_multiple_videos.html

There is a strange behavious in Master version,
if after loop ends you press play , the audio start but video is not visible.

There are other differences too:
- if browser windows loose focus public version don't stop , master correctly stop and restart while off view

**Comment by pupunzi** [comment]
Hi,

The "paly" issue is due to an incorrect way to call the "play" action.
Instead of:
`<button class="command" onclick="jQuery('#bgndVideo').YTPGetPlayer().playVideo()"> play </button>`
you should have:
'<button class="command" onclick="jQuery('#bgndVideo').YTPPlay()"> play </button>'

That is valid for the other action available via buttons on the page (my fault :-) )

Soon I'll publish the Master as release fixing those issue.
