### ISSUE TITLE
How to auto play video without touch on mobile

### ISSUE THREAD

**Issue by abbastahir** [pupunzi/jquery.mb.YTPlayer#352]
There is no any option to auto play video without touch on mobile.
I have hide this code but same result.
jQuery(document).one("touchstart", function () {
            YTPlayer.player.playVideo();
          });

any solution?

**Comment by pupunzi** [comment]
The most of mobile devices doesn't allow video to play without a human interaction. 
I noticed that on the iPhoneX with the latest OS the video starts without the needs of the first touch but that is device dependent. don't remove those lines otherwise the most of devices will not be able to watch the video.

**Comment by abbastahir** [comment]
Thanks.
