### ISSUE TITLE
Video is blurry

### ISSUE THREAD

**Issue by ithelpme** [pupunzi/jquery.mb.YTPlayer#423]
JoomLead offers this integration as a free Joomla Gantry particles.  https://joomlead.com/gantry-5-particles/

The video background works nice but any videos I use turns out blurry. I’adjusted the quality to High but no luck. Here’s my website http://www.hairdeluxelodi.com
I have the video loaded on the main page. I’ve tried various videos and it’s all blurry. Here’s the same website on WIX and you can see the background video is high resolution. https://phyrun7.wixsite.com/hairdeluxe 
Any help is appreciated. I also posted this on JoomLead support page and they referred me directly to the developer of this YTPlayer. https://joomlead.com/forums/topic/jl-video-background-blurry/#post-164792
Thank you.

**Comment by pupunzi** [comment]
Hi,
Did you try to set the "body" as containment of the YTPlayer?

Your video is blurry because is set as background of a very high container causing the inclusion of a really big iframe to fit the containment. The youtube iframe in your case is: 8901px x 5006.4px and the video definition is lower.

Setting the "body" as containment the max height would be the windows height and the iframe would be the right dimension.

**Comment by ithelpme** [comment]
Hello, in the Gantry framework in Joomla, the Body element doesn't have an ID tag by default, but it's easy to add the ID tag.  I added the "testbody" ID and in the particles configuration, instead of using "g-features" for the section ID, I used testbody for the Element ID.  The video background doesn't appear.  My Internet Download Manager, IDM, senses there's a video because I can download a video.  It seems the video is playing in the background and not the foreground.  I'm no expert in css or coding but I think the overall issue is what you mentioned but my video isn't appearing when I try to contain it in the body tag.  I only works in a section containment in the Gantry framework.

**Comment by pupunzi** [comment]
Probably you have elements that covers the body of your page.
If you want to set the video as background of a page section that section should not be the main section that can grow in its eight but a dedicated fixed height section. Otherwise you should set it as body background and modify the CSS to let the video be visible.

![screenshot-github com-2019 02 05-11-47-37](https://user-images.githubusercontent.com/56659/52268523-0fb7ef80-293c-11e9-930b-75c62642d58e.png)

**Comment by ithelpme** [comment]
Hello, sorry for the delayed response. Working with another person, we were able to put the video as a background and we are seeing the video now.  Background isn't allowed to "grow" in height but video is still blurry.  Would you be able to look at the website and look at the source code.  You'll see that we gave the body div id <div id="g-page-surround".  Thank you.
