### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by nascimentohugo** [pupunzi/jquery.mb.YTPlayer#429]
My website console JavaScript states the following message:

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').
...
www-widgetapi.js:100 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://www.storiesmadevisual.com').
...
You can check the website.
This started to happen after I've changed from http to https.
Support theme says it's a ytp plugin issue.

Can anyone help?
Thanks

**Comment by pupunzi** [comment]
Hi,
This is an old Youtube issue that happens if you are logged on Youtube. It is not a blocking error and has no fix at the time. Someone is suggesting to call the iframe API using the www. I just changed the call as they suggest. If you download the master copy should already be corrected.

All the best,
Matteo
