### ISSUE TITLE
Not embeddable error causes endless loop

### ISSUE THREAD

**Issue by xmztools** [pupunzi/jquery.mb.YTPlayer#445]
I have an issue with the error functionality for videos that can't be embedded. The app that I'm making has the ability to let the user change the video dynamically based on their own input. I know you can check whether the player causes an error if it isn't embeddable using onError, which is what I'm doing. However, if I change the current video to one that can't be embedded using YTPChangeMovie and it triggers this error state, then afterwards whenever I try to change the video to different one that I know for sure actually is embeddable, it always enters an endless loop that continuously executes the onReady state and the video does not play. It almost seems as if the error is crashing the YTPlayer. Is there something specific you have to do when you catch the error to prevent this from happening? Any help would be appreciated. Thanks!

**Comment by bilo1967** [comment]
Hi, 

I'm experiencing the same error, which does not involve embeddable videos only but seems related to error handling in general. 

As a proof of concept, I'm using [one of your demo pages](https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html).

- insert a non existing YT video ID in the "change video" form at bottom right.
- press the "change video button"

Now "undefined" is displayed in the "current video" right under the previous form.

Neither if you press one of the "Change video 1,2,3" buttons nor if you insert an existing video ID in the "change video" form  the video is now displayed.  This happens either with Chrome and with Firefox. With firefox when you insert the wrong ID and then press "Change video 2" it seems that the player gets stuck in an infinite start/stop loop.

I've compiled a similar page enabling the YTPReady event. It seems that when you try to load a "good" video after an error, this event is fired continuously.

One more thing. I see that it's not possible to create the player without specifying an existing video. I understand that this component is basically designed for background videos, but since the embedded version is excellent too, it would be nice to have the player ready but empty and load videos dynamically when needed.

(Comunque complimenti e grazie, davvero un ottimo componente. Sto cercando di proiettare lo stesso video video su due client diversi collegati via WebRTC in modo il più possibile sincronizzato e il tuo componente esporta gli eventi giusti delle API di Youtube, oltre ad essere molto "pulito" e ottimamente integrato con JQuery).

**Comment by pupunzi** [comment]
@bilo1967 @xmztools 
With the new 3.3.1 release, this bug has been fixed.

@bilo1967 Grazie per i complimenti :-)
