### ISSUE TITLE
Issue with multiple players

### ISSUE THREAD

**Issue by leo10in01** [pupunzi/jquery.mb.YTPlayer#89]
Hi,

first of all, thanks for the great player! 
I noticed an issue by using multiple players for several projects on my website. 
If i play Video A - It works perfectly. If i go to Video B and press play i get an error - white screen. 
After refreshing video B it works... and so on.. 

This is the url with the used template: batz-originals.com/agency

Console errors:
FIREFOX: TypeError: YTPlayer.player is undefined
CHROME: Uncaught TypeError: Cannot read property 'playVideo' of undefined

**Comment by pupunzi** [comment]
Hi,
The YTPlayer plugin works fine with multiple instances in a single page; as I can see the plugin has been integrated in the Theme you are using so you should ask the Theme author to fix the issue also because the site is getting content via AJAX and the correct behavior depends on how the player is initialize once injected into the page.

Bye,
Matteo
